// chapters/09_appendix/tables.typ
// Note: figures wrapped in [...] so <labels> are in markup mode (not code mode)

// ── General structure of the attached annex file ──────────────────────────────
#let annex-structure-table = [
  #figure(
    table(
      columns:  (auto, 1fr),
      stroke:   0.5pt,
      align:    (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*Directory*],
      table.cell(fill: luma(239))[*Content*],

      [`./`],
        [Contains a `README.TXT` explaining this structure.],
      [`./<project_name>`],
        [Development directory structure (see @tab:dev-dir-structure).],
      [`./installation`],
        [Files for installation or a document explaining where to download 3rd party
         software and corresponding versions.],
      [`./documentation`],
        [PDF documentation (this document and others).],
      [`./exploitation`],
        [Database scripts and 3rd party software requirements for execution (e.g., Web
         Server).],
    ),
    caption: [General structure of the attached annex file.],
  ) <tab:annex-structure>
]

// ── Recommended "Development" directory structure ─────────────────────────────
#let dev-dir-structure-table = [
  #figure(
    table(
      columns:  (auto, 1fr),
      stroke:   0.5pt,
      align:    (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*Directory*],
      table.cell(fill: luma(239))[*Content*],

      [`./`],      [IDE project files.],
      [`./src`],   [Source code files.],
      [`./src/sql`],
        [SQL scripts for database construction and initial data.],
      [`./lib`],
        [External libraries (.jar, .dll, ...) required for compilation and distribution.],
      [`./test`],
        [Base directory for all automated testing files.],
      [`./doc`],
        [Files generated by automatic tools like Javadoc.],
    ),
    caption: [Recommendation for the "development" folder structure.],
  ) <tab:dev-dir-structure>
]
