// chapters/09_appendix/tables.typ
// Note: figures wrapped in [...] so <labels> are in markup mode (not code mode)
#import "../../template.typ": risk-zone-color

// ── General structure of the attached annex file ──────────────────────────────
#let annex-structure-table = [
  #figure(
    table(
      columns:  (auto, 1fr),
      stroke:   0.5pt,
      align:    (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*Directory*],
      table.cell(fill: luma(239))[*Content*],

      [`./`],
        [Contains a `README.TXT` explaining this structure.],
      [`./<project_name>`],
        [Development directory structure (see @tab:dev-dir-structure).],
      [`./installation`],
        [Files for installation or a document explaining where to download 3rd party
         software and corresponding versions.],
      [`./documentation`],
        [PDF documentation (this document and others).],
      [`./exploitation`],
        [Database scripts and 3rd party software requirements for execution (e.g., Web
         Server).],
    ),
    caption: [General structure of the attached annex file.],
  ) <tab:annex-structure>
]

// ── Recommended "Development" directory structure ─────────────────────────────
#let dev-dir-structure-table = [
  #figure(
    table(
      columns:  (auto, 1fr),
      stroke:   0.5pt,
      align:    (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*Directory*],
      table.cell(fill: luma(239))[*Content*],

      [`./`],      [IDE project files.],
      [`./src`],   [Source code files.],
      [`./src/sql`],
        [SQL scripts for database construction and initial data.],
      [`./lib`],
        [External libraries (.jar, .dll, ...) required for compilation and distribution.],
      [`./test`],
        [Base directory for all automated testing files.],
      [`./doc`],
        [Files generated by automatic tools like Javadoc.],
    ),
    caption: [Recommendation for the "development" folder structure.],
  ) <tab:dev-dir-structure>
]

// ── Risk probability scale ──────────────────────────────────────────────────
#let probability-scale-table = [
  #figure(
    table(
      columns: (auto, auto, 1fr),
      stroke:  0.5pt,
      align:   (left + horizon, center + horizon, center + horizon),

      table.cell(fill: luma(239))[*Label*],
      table.cell(fill: luma(239))[*Range*],
      table.cell(fill: luma(239))[*Value used for calculations*],

      [Very Low],  [\[0%-20%\]],    [10%],
      [Low],       [(20%-40%\]],    [30%],
      [Medium],    [(40%-60%\]],    [50%],
      [High],      [(60%-80%\]],    [70%],
      [Very High], [(80%-100%\]],   [90%],
    ),
    caption: [Risk probability scale.],
  ) <tab:probability-scale>
]

// ── Risk impact scale ───────────────────────────────────────────────────────
#let impact-scale-table = [
  #figure(
    {
      set text(size: 9pt)
      table(
        columns: (auto, auto, auto, auto, auto, auto),
        stroke:  0.5pt,
        align:   (left + horizon,) + (left + horizon,) * 5,

        table.cell(fill: luma(239))[*Objective*],
        table.cell(fill: luma(239))[*Very Low / 5%*],
        table.cell(fill: luma(239))[*Low / 10%*],
        table.cell(fill: luma(239))[*Moderate / 20%*],
        table.cell(fill: luma(239))[*High / 40%*],
        table.cell(fill: luma(239))[*Very High / 80%*],

        [*Cost*],
          [Insignificant cost increase],
          [Cost increase < 10%],
          [Cost increase 10-20%],
          [Cost increase 20-40%],
          [Cost increase > 40%],

        [*Schedule*],
          [Insignificant time increase],
          [Time increase < 5%],
          [Time increase 5-10%],
          [Time increase 10-20%],
          [Time increase > 20%],

        [*Scope*],
          [Barely noticeable scope reduction],
          [Minor areas of scope affected],
          [Major areas of scope affected],
          [Scope reduction unacceptable to the stakeholders],
          [The delivered scope is effectively useless],

        [*Quality*],
          [Barely noticeable quality degradation],
          [Only very demanding applications are affected],
          [Quality reduction requires stakeholder acceptance],
          [Quality reduction unacceptable to the stakeholders],
          [The end result is effectively useless],
      )
    },
    caption: [Risk impact scale across the four project objectives.],
  ) <tab:impact-scale>
]

// ── Probability-Impact Matrix ───────────────────────────────────────────────
// Cell value = Probability x Impact. Coloured by zone: green (low priority),
// yellow (moderate priority), red (high priority - requires a contingency plan).
#let probability-impact-matrix-table = [
  #figure(
    {
      set text(size: 9pt)
      let z(v, zone) = table.cell(fill: risk-zone-color(zone), align: center + horizon)[#v]
      table(
        columns: (auto, 1fr, 1fr, 1fr, 1fr, 1fr),
        stroke:  0.5pt,
        align:   center + horizon,

        table.cell(fill: luma(239))[*Probability \\ Impact*],
        table.cell(fill: luma(239))[0.05 \ Very Low],
        table.cell(fill: luma(239))[0.10 \ Low],
        table.cell(fill: luma(239))[0.20 \ Moderate],
        table.cell(fill: luma(239))[0.40 \ High],
        table.cell(fill: luma(239))[0.80 \ Very High],

        table.cell(fill: luma(239))[0.90 \ Very High],
          z("0.05", "green"), z("0.09", "yellow"), z("0.18", "red"), z("0.36", "red"), z("0.72", "red"),
        table.cell(fill: luma(239))[0.70 \ High],
          z("0.04", "green"), z("0.07", "yellow"), z("0.14", "yellow"), z("0.28", "red"), z("0.56", "red"),
        table.cell(fill: luma(239))[0.50 \ Medium],
          z("0.03", "green"), z("0.05", "green"), z("0.10", "yellow"), z("0.20", "red"), z("0.40", "red"),
        table.cell(fill: luma(239))[0.30 \ Low],
          z("0.02", "green"), z("0.03", "green"), z("0.06", "yellow"), z("0.12", "yellow"), z("0.24", "red"),
        table.cell(fill: luma(239))[0.10 \ Very Low],
          z("0.01", "green"), z("0.01", "green"), z("0.02", "green"), z("0.04", "green"), z("0.08", "yellow"),
      )
    },
    caption: [Probability-Impact Matrix. Green: low priority (score $<=$ 0.05).
              Yellow: moderate priority (0.06-0.14). Red: high priority,
              requires a contingency plan (score $>=$ 0.18).],
  ) <tab:pi-matrix>
]

// ── Delivered files ─────────────────────────────────────────────────────────
#let delivery-table = [
  #figure(
    table(
      columns: (auto, 1fr),
      stroke:  0.5pt,
      align:   (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*File*],
      table.cell(fill: luma(239))[*Description*],

      [`TFG_Mario_Orviz.pdf`],
        [This document (technical report).],
      [`README.txt`],
        [Plain-text file containing the URL of the public GitHub repository and
         the URL of the live deployed application.],
    ),
    caption: [Files included in the physical submission.],
  ) <tab:delivery>
]

// ── GitHub repository structure ──────────────────────────────────────────────
#let repo-structure-table = [
  #figure(
    table(
      columns: (auto, 1fr),
      stroke:  0.5pt,
      align:   (left + horizon, left + horizon),

      table.cell(fill: luma(239))[*Path*],
      table.cell(fill: luma(239))[*Description*],

      [`api/`],
        [FastAPI backend.],
      [`api/controllers/`],
        [HTTP layer: route handlers; no business logic.],
      [`api/services/`],
        [Business logic: simulation algorithm, analytics, authentication.],
      [`api/repositories/`],
        [Database access layer (SQLAlchemy queries).],
      [`api/schemas.py`],
        [Input DTOs (Pydantic); all input validation lives here.],
      [`api/records.py`],
        [Output domain records returned by the API.],
      [`api/main.py`],
        [App factory; registers routers and CORS middleware.],
      [`frontend/`],
        [Python Shiny web application.],
      [`frontend/app.py`],
        [Main entry point; all four UI tabs.],
      [`frontend/components/`],
        [Reusable UI widgets (matrix editor, simulation panel, etc.).],
      [`frontend/locales/`],
        [i18n translation files (English, Spanish, Asturian, Galician,
         Basque, Catalan).],
      [`db/`],
        [ORM models, session factory, and COMPADRE/COMADRE seed scripts.],
      [`alembic/`],
        [Database migration files; applied automatically on container start.],
      [`tests/`],
        [Integration tests (require a running PostgreSQL instance).],
      [`tests/unit/`],
        [Unit tests with no database required; use `unittest.mock`.],
      [`tests/e2e/`],
        [End to end tests],
      [`.github/workflows/`],
        [CI/CD pipelines: unit + integration tests, Bandit/pip-audit security
         scans, and CodeQL static analysis.],
      [`docker-compose.yml`],
        [Local multi-service stack (`api` + `frontend` + `db`).],
      [`Dockerfile`],
        [Docker image for the API service (also used locally for the frontend).],
      [`Dockerfile.frontend`],
        [Entrypoint-less image for the Railway frontend service.],
      [`Makefile`],
        [Developer shortcuts (`make up`, `make down`, `make logs`).],
      [`requirements.txt`],
        [Python runtime dependencies.],
      [`tfg-doc/`],
        [Typst source files for this document.],
    ),
    caption: [Structure of the public GitHub repository
              (#link("https://github.com/orvizz/population-growth-simulator")).],
  ) <tab:repo-structure>
]

// ── Opportunity Probability-Impact Matrix ───────────────────────────────────
// Same grid and colour zones as probability-impact-matrix-table above, the
// methodology is identical, only the meaning of "act on it" flips from
// mitigating a threat to exploiting an opportunity.
#let opportunity-probability-impact-matrix-table = [
  #figure(
    {
      set text(size: 9pt)
      let z(v, zone) = table.cell(fill: risk-zone-color(zone), align: center + horizon)[#v]
      table(
        columns: (auto, 1fr, 1fr, 1fr, 1fr, 1fr),
        stroke:  0.5pt,
        align:   center + horizon,

        table.cell(fill: luma(239))[*Probability \\ Impact*],
        table.cell(fill: luma(239))[0.05 \ Very Low],
        table.cell(fill: luma(239))[0.10 \ Low],
        table.cell(fill: luma(239))[0.20 \ Moderate],
        table.cell(fill: luma(239))[0.40 \ High],
        table.cell(fill: luma(239))[0.80 \ Very High],

        table.cell(fill: luma(239))[0.90 \ Very High],
          z("0.05", "green"), z("0.09", "yellow"), z("0.18", "red"), z("0.36", "red"), z("0.72", "red"),
        table.cell(fill: luma(239))[0.70 \ High],
          z("0.04", "green"), z("0.07", "yellow"), z("0.14", "yellow"), z("0.28", "red"), z("0.56", "red"),
        table.cell(fill: luma(239))[0.50 \ Medium],
          z("0.03", "green"), z("0.05", "green"), z("0.10", "yellow"), z("0.20", "red"), z("0.40", "red"),
        table.cell(fill: luma(239))[0.30 \ Low],
          z("0.02", "green"), z("0.03", "green"), z("0.06", "yellow"), z("0.12", "yellow"), z("0.24", "red"),
        table.cell(fill: luma(239))[0.10 \ Very Low],
          z("0.01", "green"), z("0.01", "green"), z("0.02", "green"), z("0.04", "green"), z("0.08", "yellow"),
      )
    },
    caption: [Opportunity Probability-Impact Matrix. Green: low priority, simply
              monitored. Yellow: moderate priority, actively enhanced. Red: high
              priority (score $>=$ 0.18), requires a dedicated exploitation
              plan.],
  ) <tab:opp-pi-matrix>
]
