services:
  db:
    image: postgres:16-alpine
    container_name: tfg_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dlsh9384hfndo23
      POSTGRES_DB: matrix_db
    ports:
      - "5435:5432"  # Changed host port to 5435
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: